import { TBillFormContent } from '@/models';

const billformConf: TBillFormContent | undefined = {
  action: 1,
  billFormType: 'Single',
  componentModuleName: '公共属性',
  componentName: '公共属性',
  displayName: '公共属性',
  idBillForm: 'bp7vPdL92lBY7m63E2VSy',
  idComponent: '0000-d711b775-a2b9-4028-b714-1f7664b310a8',
  idComponentModule: '0000-ae91cf86-2dba-4906-8fbc-b5e35d71909a',
  idProject: '0000-fe135b87-fb33-481f-81a6-53dff1808f43',
  idSubProject: '0000-bb004a40-3b38-4c9c-9f30-b69a543b0598',
  name: 'CommonAttribute',
  projectName: '模板代码设计工具RUST',
  subProjectName: '模型管理',
  configList: {
    idBillForm: 'N_PNMSb9-NSAlHkGLv3sr',
    name: 'newBill',
    displayName: '新表单',
    header: [
      {
        idBillFormTab: 'b6NWuENlbJqnAu8i0Wftd',
        tabCode: 'commonAttribute',
        tabName: '公共属性',
        tabIndex: 0,
        billFormFields: [
          {
            idBillFormField: 'n-eI7RINUfGlw5P9NdGRI',
            name: 'idCommonAttribute',
            displayName: '属性id',
            fgMainProperty: true,
            showOrder: 0,
            readonly: false,
            dataType: 'PK',
            inputType: 'Input',
            fgDisplay: false,
          },
          {
            idBillFormField: 'w2Sb8CezqrrmeU_J_vJEQ',
            name: 'attributeName',
            displayName: '属性名称',
            fgMainProperty: false,
            showOrder: 1,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'HxgEr8MIMqTpkEMRraB8F',
            name: 'displayName',
            displayName: '显示名称',
            fgMainProperty: false,
            showOrder: 2,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'cmkgEDvxoTd80HfyIr2zw',
            name: 'columnName',
            displayName: '字段名称',
            fgMainProperty: false,
            showOrder: 3,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 't87weljLlp5tQW1iZLnNr',
            name: 'idDataType',
            dataType: 'InternalRef',
            displayName: '数据类型',
            fgMainProperty: false,
            showOrder: 4,
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'treeTable',
              title: '数据类型',
              displayProp: 'displayName',
              backWriteProp: 'idDataType',
              billTreeRef: {
                uri: '/project/aqDetail',
                method: 'POST',
                keyAttr: 'idProject',
                labelAttr: 'displayName',
              },
              tableRef: {
                dataUri: '/dataType/aqPage',
                tableMainProp: 'idDataType',
                treeRefMainKey: 'idProject',
                idComponentEntity: '0000-7b89236a-d59a-409d-8980-c7385efba924',
                ceDisplayName: '数据类型',
                refColumns: [
                  {
                    idBillRefColumn: 'xWs0_0yLioEqnu7A0FWFU',
                    name: 'code',
                    displayName: '数据类型编码',
                  },
                  {
                    idBillRefColumn: 'woBF6HtxMzYkUT2tQq54s',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                  {
                    idBillRefColumn: 'if5_eyqPT2CcDitaFk34j',
                    name: 'sn',
                    displayName: '序列号',
                  },
                  {
                    idBillRefColumn: 'Md1lPdbzY8B6iec8toWVo',
                    name: 'columnType',
                    displayName: '字段类型',
                  },
                  {
                    idBillRefColumn: 'tlZu7GDaXlvs9wJJSAvrP',
                    name: 'project.displayName',
                    displayName: '项目',
                    dataType: '',
                  },
                ],
                searchRefs: [
                  {
                    idBillSearchRef: 'uvEwN1GdpIU2TGlFKRfT_',
                    operatorCode: 'like',
                    attributeName: 'code',
                    label: '数据类型编码',
                    searchAttributes: ['code'],
                    htmlInputType: 'Input',
                    showOrder: 0,
                  },
                  {
                    idBillSearchRef: '_3T-B5Je9-IzlBgtG3ATJ',
                    operatorCode: 'like',
                    attributeName: 'displayName',
                    label: '显示名称',
                    searchAttributes: ['displayName'],
                    htmlInputType: 'Input',
                    showOrder: 0,
                  },
                ],
              },
            },
            fgDisplay: true,
            refAttributeName: 'dataType',
          },
          {
            idBillFormField: '7D0v5WPU9j5Uq8T0yaI5g',
            name: 'idProject',
            dataType: 'InternalRef',
            displayName: '项目',
            fgMainProperty: false,
            showOrder: 5,
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '项目',
              displayProp: 'code',
              backWriteProp: 'idProject',
              tableRef: {
                dataUri: '/project/aqPage',
                tableMainProp: 'idProject',
                idComponentEntity: '0000-c42a3d77-90bd-4e33-8618-dc6b746109f7',
                ceDisplayName: '项目',
                refColumns: [
                  {
                    idBillRefColumn: 'FRDdxJIcg-GhAvyL23d3s',
                    name: 'code',
                    displayName: '项目编号',
                  },
                  {
                    idBillRefColumn: 'L-E35XJrfb7HrXgk-56NN',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                  {
                    idBillRefColumn: 'mHq8o9dYpLPUbub7SVBdw',
                    name: 'templateCode',
                    displayName: '项目模板编号',
                  },
                  {
                    idBillRefColumn: 'pKzISEsu5lqk95yhnnwKb',
                    name: 'fileNameType',
                    displayName: '文件名样式',
                  },
                ],
              },
            },
            fgDisplay: true,
            fgTreeAttr: true,
            refAttributeName: 'project',
          },
          {
            idBillFormField: 'iITPAG01_0eXevAfB9PQr',
            name: 'len',
            displayName: '数据长度',
            fgMainProperty: false,
            showOrder: 6,
            readonly: false,
            dataType: 'Integer',
            inputType: 'InputNumber',
            fgDisplay: true,
          },
          {
            idBillFormField: 'QxQlGTx5s-909KqSNS7PX',
            name: 'pcs',
            displayName: '精度',
            fgMainProperty: false,
            showOrder: 7,
            readonly: false,
            dataType: 'Integer',
            inputType: 'InputNumber',
            fgDisplay: true,
          },
          {
            idBillFormField: 'HKmUGhXzuuC78egw63r55',
            name: 'fgMandatory',
            displayName: '是否必填',
            fgMainProperty: false,
            showOrder: 8,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
          },
          {
            idBillFormField: 'GugXNdyWkBmv8PMIRuuwI',
            name: 'sn',
            displayName: '序号',
            fgMainProperty: false,
            showOrder: 9,
            readonly: false,
            dataType: 'Integer',
            inputType: 'InputNumber',
            fgDisplay: true,
          },
          {
            idBillFormField: 'DU2IhhFenIAwkjNqPpv0H',
            name: 'defaultValue',
            displayName: '默认值',
            fgMainProperty: false,
            showOrder: 10,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: '--qe4KceW9UPvTJ5j5zH7',
            name: 'refDisplayName',
            displayName: '引用属性显示名称',
            fgMainProperty: false,
            showOrder: 11,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'cOWaf_zOXM4iOJp_u_i0u',
            name: 'category',
            displayName: '属性类别',
            fgMainProperty: false,
            showOrder: 12,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'fQjGO96OT5m6KvoxQc_Oc',
            name: 'refAttributeName',
            displayName: '引用属性名称',
            fgMainProperty: false,
            showOrder: 13,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'nxMRbZwODdhNxggQdGNDr',
            name: 'idRefEntity',
            dataType: 'InternalRef',
            displayName: '上级实体信息',
            fgMainProperty: false,
            showOrder: 14,
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '实体信息',
              displayProp: 'displayName',
              backWriteProp: 'idEntity',
              tableRef: {
                dataUri: '/ddEntity/aqPage',
                tableMainProp: 'idEntity',
                idComponentEntity: '0000-10940214-e5d9-4dce-b707-191e200c695f',
                ceDisplayName: '实体信息',
                refColumns: [
                  {
                    idBillRefColumn: 'areiFvqcjsksTwpnQDV7l',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                  {
                    idBillRefColumn: 'WNJ0GAeGY6Hft87kK8iDI',
                    name: 'className',
                    displayName: '类名',
                  },
                  {
                    idBillRefColumn: 'OUDIK37JRUiZcigC8iA2f',
                    name: 'tableName',
                    displayName: '表名',
                  },
                ],
              },
            },
            fgDisplay: true,
            refAttributeName: 'refEntity',
          },
        ],
        metadataAttrName: 'commonAttribute',
        firstUpperTabCode: 'CommonAttribute',
        fgDefaultTab: true,
        tabClassName: 'CommonAttribute',
        firstLowerTabClassName: 'commonAttribute',
        tabAttrName: 'commonAttribute',
        firstUpperTabAttrName: 'CommonAttribute',
        mainProperty: 'idCommonAttribute',
        refType: null,
        orderProperty: 'sn',
        orderType: 'ASC',
      },
    ],
    body: [],
    tail: [],
    uriConf: {
      page: '/commonAttribute/aqPage',
      fetchById: '/commonAttribute/getById',
      batchRemove: '/commonAttribute/batchRemove',
    },
  },
  configForm: {
    idBillForm: 'N_PNMSb9-NSAlHkGLv3sr',
    name: 'newBill',
    displayName: '新表单',
    header: [
      {
        idBillFormTab: 'b6NWuENlbJqnAu8i0Wftd',
        tabCode: 'commonAttribute',
        tabName: '公共属性',
        tabIndex: 0,
        billFormFields: [
          {
            idBillFormField: 'n-eI7RINUfGlw5P9NdGRI',
            name: 'idCommonAttribute',
            displayName: '属性id',
            fgMainProperty: true,
            showOrder: 0,
            readonly: false,
            dataType: 'PK',
            inputType: 'Input',
            fgDisplay: false,
          },
          {
            idBillFormField: 'w2Sb8CezqrrmeU_J_vJEQ',
            name: 'attributeName',
            displayName: '属性名称',
            fgMainProperty: false,
            showOrder: 1,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'HxgEr8MIMqTpkEMRraB8F',
            name: 'displayName',
            displayName: '显示名称',
            fgMainProperty: false,
            showOrder: 2,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'cmkgEDvxoTd80HfyIr2zw',
            name: 'columnName',
            displayName: '字段名称',
            fgMainProperty: false,
            showOrder: 3,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 't87weljLlp5tQW1iZLnNr',
            name: 'idDataType',
            dataType: 'InternalRef',
            displayName: '数据类型',
            fgMainProperty: false,
            showOrder: 4,
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '数据类型',
              displayProp: 'displayName',
              backWriteProp: 'idDataType',
              tableRef: {
                dataUri: '/dataType/aqPage',
                tableMainProp: 'idDataType',
                treeRefMainKey: '',
                idComponentEntity: 'cTJfrDaUS3jn7tjORhO_4',
                ceDisplayName: '数据类型',
                refColumns: [
                  {
                    idBillRefColumn: 'xWs0_0yLioEqnu7A0FWFU',
                    name: 'code',
                    displayName: '数据类型编码',
                  },
                  {
                    idBillRefColumn: 'woBF6HtxMzYkUT2tQq54s',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                  {
                    idBillRefColumn: 'if5_eyqPT2CcDitaFk34j',
                    name: 'sn',
                    displayName: '序列号',
                  },
                  {
                    idBillRefColumn: 'Md1lPdbzY8B6iec8toWVo',
                    name: 'columnType',
                    displayName: '字段类型',
                  },
                  {
                    idBillRefColumn: 'tlZu7GDaXlvs9wJJSAvrP',
                    name: 'project.displayName',
                    displayName: '项目',
                    dataType: '',
                  },
                ],
                searchRefs: [
                  {
                    idBillSearchRef: 'yC20g4201bfWHaeoVjtHT',
                    operatorCode: 'like',
                    attributeName: 'code',
                    label: '数据类型编码',
                    searchAttributes: ['code'],
                    htmlInputType: 'Input',
                    showOrder: 0,
                  },
                  {
                    idBillSearchRef: 'x9QzBWY2hXg99NgOBsqBQ',
                    operatorCode: 'like',
                    attributeName: 'displayName',
                    label: '显示名称',
                    searchAttributes: ['displayName'],
                    htmlInputType: 'Input',
                    showOrder: 0,
                  },
                  {
                    idBillSearchRef: 'SGjyL77tQ13lovJvKXqSD',
                    operatorCode: 'equal',
                    attributeName: 'fgPreset',
                    label: '系统预置数据标识',
                    searchAttributes: ['fgPreset'],
                    htmlInputType: 'Checkbox',
                    showOrder: 0,
                    valueType: 'Bool',
                  },
                ],
              },
            },
            fgDisplay: true,
            refAttributeName: 'dataType',
          },
          {
            idBillFormField: '7D0v5WPU9j5Uq8T0yaI5g',
            name: 'idProject',
            dataType: 'InternalRef',
            displayName: '项目',
            fgMainProperty: false,
            showOrder: 5,
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '项目',
              displayProp: 'code',
              backWriteProp: 'idProject',
              tableRef: {
                dataUri: '/project/aqPage',
                tableMainProp: 'idProject',
                idComponentEntity: '0000-c42a3d77-90bd-4e33-8618-dc6b746109f7',
                ceDisplayName: '项目',
                refColumns: [
                  {
                    idBillRefColumn: 'FRDdxJIcg-GhAvyL23d3s',
                    name: 'code',
                    displayName: '项目编号',
                  },
                  {
                    idBillRefColumn: 'L-E35XJrfb7HrXgk-56NN',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                  {
                    idBillRefColumn: 'mHq8o9dYpLPUbub7SVBdw',
                    name: 'templateCode',
                    displayName: '项目模板编号',
                  },
                  {
                    idBillRefColumn: 'pKzISEsu5lqk95yhnnwKb',
                    name: 'fileNameType',
                    displayName: '文件名样式',
                  },
                ],
              },
            },
            fgDisplay: true,
            fgTreeAttr: true,
            refAttributeName: 'project',
          },
          {
            idBillFormField: 'iITPAG01_0eXevAfB9PQr',
            name: 'len',
            displayName: '数据长度',
            fgMainProperty: false,
            showOrder: 6,
            readonly: false,
            dataType: 'Integer',
            inputType: 'InputNumber',
            fgDisplay: true,
          },
          {
            idBillFormField: 'QxQlGTx5s-909KqSNS7PX',
            name: 'pcs',
            displayName: '精度',
            fgMainProperty: false,
            showOrder: 7,
            readonly: false,
            dataType: 'Integer',
            inputType: 'InputNumber',
            fgDisplay: true,
          },
          {
            idBillFormField: 'HKmUGhXzuuC78egw63r55',
            name: 'fgMandatory',
            displayName: '是否必填',
            fgMainProperty: false,
            showOrder: 8,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
          },
          {
            idBillFormField: 'GugXNdyWkBmv8PMIRuuwI',
            name: 'sn',
            displayName: '序号',
            fgMainProperty: false,
            showOrder: 9,
            readonly: false,
            dataType: 'Integer',
            inputType: 'InputNumber',
            fgDisplay: true,
          },
          {
            idBillFormField: 'DU2IhhFenIAwkjNqPpv0H',
            name: 'defaultValue',
            displayName: '默认值',
            fgMainProperty: false,
            showOrder: 10,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: '--qe4KceW9UPvTJ5j5zH7',
            name: 'refDisplayName',
            displayName: '引用属性显示名称',
            fgMainProperty: false,
            showOrder: 11,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'cOWaf_zOXM4iOJp_u_i0u',
            name: 'category',
            displayName: '属性类别',
            fgMainProperty: false,
            showOrder: 12,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'fQjGO96OT5m6KvoxQc_Oc',
            name: 'refAttributeName',
            displayName: '引用属性名称',
            fgMainProperty: false,
            showOrder: 13,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
          },
          {
            idBillFormField: 'nxMRbZwODdhNxggQdGNDr',
            name: 'idRefEntity',
            dataType: 'InternalRef',
            displayName: '上级实体信息',
            fgMainProperty: false,
            showOrder: 14,
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '实体信息',
              displayProp: 'displayName',
              backWriteProp: 'idEntity',
              tableRef: {
                dataUri: '/ddEntity/aqPage',
                tableMainProp: 'idEntity',
                idComponentEntity: '0000-10940214-e5d9-4dce-b707-191e200c695f',
                ceDisplayName: '实体信息',
                refColumns: [
                  {
                    idBillRefColumn: 'areiFvqcjsksTwpnQDV7l',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                  {
                    idBillRefColumn: 'WNJ0GAeGY6Hft87kK8iDI',
                    name: 'className',
                    displayName: '类名',
                  },
                  {
                    idBillRefColumn: 'OUDIK37JRUiZcigC8iA2f',
                    name: 'tableName',
                    displayName: '表名',
                  },
                ],
              },
            },
            fgDisplay: true,
            refAttributeName: 'refEntity',
          },
        ],
        metadataAttrName: 'commonAttribute',
        firstUpperTabCode: 'CommonAttribute',
        fgDefaultTab: true,
        tabClassName: 'CommonAttribute',
        firstLowerTabClassName: 'commonAttribute',
        tabAttrName: 'commonAttribute',
        firstUpperTabAttrName: 'CommonAttribute',
        mainProperty: 'idCommonAttribute',
        refType: null,
        orderProperty: 'sn',
        orderType: 'ASC',
      },
    ],
    body: [],
    tail: [],
    uriConf: {
      fetchById: '/commonAttribute/getById',
      save: '/commonAttribute/add',
      update: '/commonAttribute/update',
      dataRemove: '/commonAttribute/remove',
    },
  },
};

export { billformConf };
