import { TBillFormContent } from '@/models';

const tableConf: TBillFormContent | undefined = {
  action: 1,
  billFormType: 'Single',
  componentModuleName: '公共属性',
  componentName: '公共属性',
  displayName: '公共属性',
  idBillForm: 'bp7vPdL92lBY7m63E2VSy',
  idComponent: '0000-d711b775-a2b9-4028-b714-1f7664b310a8',
  idComponentModule: '0000-ae91cf86-2dba-4906-8fbc-b5e35d71909a',
  idProject: '0000-fe135b87-fb33-481f-81a6-53dff1808f43',
  idSubProject: '0000-bb004a40-3b38-4c9c-9f30-b69a543b0598',
  name: 'CommonAttribute',
  projectName: '模板代码设计工具RUST',
  subProjectName: '模型管理',
  configList: {
    idBillForm: 'N_PNMSb9-NSAlHkGLv3sr',
    name: 'newBill',
    displayName: '新表单',
    header: [
      {
        idBillFormTab: 'b6NWuENlbJqnAu8i0Wftd',
        tabCode: 'commonAttribute',
        tabName: '公共属性',
        tabIndex: 0,
        billFormFields: [
          {
            idBillFormField: 'LuziGsWtzt0yqvEhkwLzO',
            name: 'idCommonAttribute',
            displayName: '属性id',
            fgMainProperty: true,
            showOrder: 0,
            readonly: false,
            dataType: 'PK',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '属性id',
          },
          {
            idBillFormField: '4qipiyUB0vNguVwJNy-kX',
            name: 'attributeName',
            displayName: '属性名称',
            fgMainProperty: false,
            showOrder: 1,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '属性名称',
          },
          {
            idBillFormField: 'daCGnPywb__SQqi5WprWM',
            name: 'displayName',
            displayName: '显示名称',
            fgMainProperty: false,
            showOrder: 2,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '显示名称',
          },
          {
            idBillFormField: 'ckMwg7CDrIEe5zFgtnHPI',
            name: 'columnName',
            displayName: '字段名称',
            fgMainProperty: false,
            showOrder: 3,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '字段名称',
          },
          {
            idBillFormField: 'g-A3hVXCB0stS9qTtcFjw',
            name: 'defaultValue',
            displayName: '默认值',
            fgMainProperty: false,
            showOrder: 4,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '默认值',
          },
          {
            idBillFormField: 'RTw990Jh6qe_0aGqDB2fN',
            name: 'fgMandatory',
            displayName: '是否必填',
            fgMainProperty: false,
            showOrder: 5,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '是否必填',
          },
          {
            idBillFormField: 'Dunj9_WOPL5im_yu8H-jL',
            name: 'len',
            displayName: '数据长度',
            fgMainProperty: false,
            showOrder: 6,
            readonly: false,
            dataType: 'Integer',
            inputType: 'InputNumber',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '数据长度',
          },
          {
            idBillFormField: 'K5HTRP5LhqZId3uVu7MeZ',
            name: 'pcs',
            displayName: '精度',
            fgMainProperty: false,
            showOrder: 7,
            readonly: false,
            dataType: 'Integer',
            inputType: 'InputNumber',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '精度',
          },
          {
            idBillFormField: 'EP1iMZ_U6jPtPC1FFn8Sy',
            name: 'sn',
            displayName: '序号',
            fgMainProperty: false,
            showOrder: 8,
            readonly: false,
            dataType: 'Integer',
            inputType: 'InputNumber',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '序号',
          },
          {
            idBillFormField: '92IptHOY0oLgbrf0lpTDj',
            name: 'refAttributeName',
            displayName: '引用属性名称',
            fgMainProperty: false,
            showOrder: 9,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '引用属性名称',
          },
          {
            idBillFormField: 'Ra3rgx7rcKTX8eaLAfXpk',
            name: 'refDisplayName',
            displayName: '引用属性显示名称',
            fgMainProperty: false,
            showOrder: 10,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '引用属性显示名称',
          },
          {
            idBillFormField: '3BUUwke-XqKQN9Y1kUGwq',
            name: 'category',
            displayName: '属性类别',
            fgMainProperty: false,
            showOrder: 11,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '属性类别',
          },
          {
            idBillFormField: '2BTJEwOKkynq6rFrFHIxn',
            name: 'fgPreset',
            displayName: '系统预置数据标识',
            fgMainProperty: false,
            showOrder: 12,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '系统预置数据标识',
            defaultValue: 'false',
          },
          {
            idBillFormField: 'EpHM2ocUUvSHGzTmhkgwA',
            name: 'idProject',
            dataType: 'InternalRef',
            displayName: '项目',
            fgMainProperty: false,
            showOrder: 13,
            refAttributeName: 'project',
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '项目',
              displayProp: 'code',
              backWriteProp: 'idProject',
              tableRef: {
                dataUri: '/project/aqPage',
                tableMainProp: 'idProject',
                idComponentEntity: '0000-c42a3d77-90bd-4e33-8618-dc6b746109f7',
                ceDisplayName: '项目',
                refColumns: [
                  {
                    idBillRefColumn: 'J5W4Pi3ZZDe1TJgSyJOTr',
                    name: 'code',
                    displayName: '项目编号',
                  },
                  {
                    idBillRefColumn: 'Vfx5Onq6qeyBtnszfiR6m',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                  {
                    idBillRefColumn: 'ZJtgXcaecLjiGKH-pnhDl',
                    name: 'templateCode',
                    displayName: '项目模板编号',
                  },
                ],
              },
            },
            fgDisplay: true,
            width: 150,
            textLen: 140,
            fgTreeAttr: true,
          },
          {
            idBillFormField: 'UQU1-fp3AgCaCXuCMvEY6',
            name: 'idDataType',
            dataType: 'InternalRef',
            displayName: '数据类型',
            fgMainProperty: false,
            showOrder: 14,
            refAttributeName: 'dataType',
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '数据类型',
              displayProp: 'code',
              backWriteProp: 'idDataType',
              tableRef: {
                dataUri: '/dataType/aqPage',
                tableMainProp: 'idDataType',
                idComponentEntity: 'cTJfrDaUS3jn7tjORhO_4',
                ceDisplayName: '数据类型',
                refColumns: [
                  {
                    idBillRefColumn: 'm-lmJPBWwp3WR96FzBgcJ',
                    name: 'code',
                    displayName: '数据类型编码',
                  },
                  {
                    idBillRefColumn: 'MrkCA7Glj21Wb8M0hfcx2',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                  {
                    idBillRefColumn: 'TsnR_-5KZQjF2qZHNbyI1',
                    name: 'columnType',
                    displayName: '字段类型',
                  },
                ],
              },
            },
            fgDisplay: true,
            width: 150,
            textLen: 140,
          },
          {
            idBillFormField: 's8chLZ48BEGnurvPlY-rw',
            name: 'idRefEntity',
            dataType: 'InternalRef',
            displayName: '上级实体信息',
            fgMainProperty: false,
            showOrder: 15,
            refAttributeName: 'refEntity',
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '实体信息',
              displayProp: 'displayName',
              backWriteProp: 'idEntity',
              tableRef: {
                dataUri: '/ddEntity/aqPage',
                tableMainProp: 'idEntity',
                idComponentEntity: '0000-10940214-e5d9-4dce-b707-191e200c695f',
                ceDisplayName: '实体信息',
                refColumns: [
                  {
                    idBillRefColumn: '-8UYieWfmQmBKzzP6LmwI',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                  {
                    idBillRefColumn: 'r30mfWsR-WXCAIScOtYeU',
                    name: 'className',
                    displayName: '类名',
                  },
                  {
                    idBillRefColumn: 'qgrwAgFmPaT2I134NmDR0',
                    name: 'tableName',
                    displayName: '表名',
                  },
                ],
              },
            },
            fgDisplay: true,
            width: 150,
            textLen: 140,
          },
        ],
        metadataAttrName: 'commonAttribute',
        firstUpperTabCode: 'CommonAttribute',
        fgDefaultTab: true,
        tabClassName: 'CommonAttribute',
        firstLowerTabClassName: 'commonAttribute',
        tabAttrName: 'commonAttribute',
        firstUpperTabAttrName: 'CommonAttribute',
        mainProperty: 'idCommonAttribute',
        refType: 'Single',
        orderProperty: 'sn',
        orderType: 'ASC',
        orderInfoList: [
          {
            idOrderInfo: 'NR36tqkRg5e-yOcLlLOvx',
            orderProperty: 'idProject',
            orderType: 'ASC',
          },
          {
            idOrderInfo: '804Qqtc0HTY-F6pQgBOKY',
            orderProperty: 'sn',
            orderType: 'ASC',
          },
        ],
      },
    ],
    body: [],
    tail: [],
    uriConf: {
      page: '/commonAttribute/aqPage',
      fetchById: '/commonAttribute/getById',
      batchRemove: '/commonAttribute/batchRemove',
    },
  },
  configForm: {
    idBillForm: 'N_PNMSb9-NSAlHkGLv3sr',
    name: 'newBill',
    displayName: '新表单',
    header: [
      {
        idBillFormTab: 'b6NWuENlbJqnAu8i0Wftd',
        tabCode: 'commonAttribute',
        tabName: '公共属性',
        tabIndex: 0,
        billFormFields: [
          {
            idBillFormField: 'LuziGsWtzt0yqvEhkwLzO',
            name: 'idCommonAttribute',
            displayName: '属性id',
            fgMainProperty: true,
            showOrder: 0,
            readonly: false,
            dataType: 'PK',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '属性id',
          },
          {
            idBillFormField: '4qipiyUB0vNguVwJNy-kX',
            name: 'attributeName',
            displayName: '属性名称',
            fgMainProperty: false,
            showOrder: 1,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '属性名称',
          },
          {
            idBillFormField: 'daCGnPywb__SQqi5WprWM',
            name: 'displayName',
            displayName: '显示名称',
            fgMainProperty: false,
            showOrder: 2,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '显示名称',
          },
          {
            idBillFormField: 'ckMwg7CDrIEe5zFgtnHPI',
            name: 'columnName',
            displayName: '字段名称',
            fgMainProperty: false,
            showOrder: 3,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '字段名称',
          },
          {
            idBillFormField: 'g-A3hVXCB0stS9qTtcFjw',
            name: 'defaultValue',
            displayName: '默认值',
            fgMainProperty: false,
            showOrder: 4,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '默认值',
          },
          {
            idBillFormField: 'RTw990Jh6qe_0aGqDB2fN',
            name: 'fgMandatory',
            displayName: '是否必填',
            fgMainProperty: false,
            showOrder: 5,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '是否必填',
          },
          {
            idBillFormField: 'Dunj9_WOPL5im_yu8H-jL',
            name: 'len',
            displayName: '数据长度',
            fgMainProperty: false,
            showOrder: 6,
            readonly: false,
            dataType: 'Integer',
            inputType: 'InputNumber',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '数据长度',
          },
          {
            idBillFormField: 'K5HTRP5LhqZId3uVu7MeZ',
            name: 'pcs',
            displayName: '精度',
            fgMainProperty: false,
            showOrder: 7,
            readonly: false,
            dataType: 'Integer',
            inputType: 'InputNumber',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '精度',
          },
          {
            idBillFormField: 'EP1iMZ_U6jPtPC1FFn8Sy',
            name: 'sn',
            displayName: '序号',
            fgMainProperty: false,
            showOrder: 8,
            readonly: false,
            dataType: 'Integer',
            inputType: 'InputNumber',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '序号',
          },
          {
            idBillFormField: '92IptHOY0oLgbrf0lpTDj',
            name: 'refAttributeName',
            displayName: '引用属性名称',
            fgMainProperty: false,
            showOrder: 9,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '引用属性名称',
          },
          {
            idBillFormField: 'Ra3rgx7rcKTX8eaLAfXpk',
            name: 'refDisplayName',
            displayName: '引用属性显示名称',
            fgMainProperty: false,
            showOrder: 10,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '引用属性显示名称',
          },
          {
            idBillFormField: '3BUUwke-XqKQN9Y1kUGwq',
            name: 'category',
            displayName: '属性类别',
            fgMainProperty: false,
            showOrder: 11,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '属性类别',
          },
          {
            idBillFormField: '2BTJEwOKkynq6rFrFHIxn',
            name: 'fgPreset',
            displayName: '系统预置数据标识',
            fgMainProperty: false,
            showOrder: 12,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '系统预置数据标识',
            defaultValue: 'false',
          },
          {
            idBillFormField: 'EpHM2ocUUvSHGzTmhkgwA',
            name: 'idProject',
            dataType: 'InternalRef',
            displayName: '项目',
            fgMainProperty: false,
            showOrder: 13,
            refAttributeName: 'project',
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '项目',
              displayProp: 'code',
              backWriteProp: 'idProject',
              tableRef: {
                dataUri: '/project/aqPage',
                tableMainProp: 'idProject',
                idComponentEntity: '0000-c42a3d77-90bd-4e33-8618-dc6b746109f7',
                ceDisplayName: '项目',
                refColumns: [
                  {
                    idBillRefColumn: 'J5W4Pi3ZZDe1TJgSyJOTr',
                    name: 'code',
                    displayName: '项目编号',
                  },
                  {
                    idBillRefColumn: 'Vfx5Onq6qeyBtnszfiR6m',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                  {
                    idBillRefColumn: 'ZJtgXcaecLjiGKH-pnhDl',
                    name: 'templateCode',
                    displayName: '项目模板编号',
                  },
                ],
              },
            },
            fgDisplay: true,
            width: 150,
            textLen: 140,
            fgTreeAttr: true,
          },
          {
            idBillFormField: 'UQU1-fp3AgCaCXuCMvEY6',
            name: 'idDataType',
            dataType: 'InternalRef',
            displayName: '数据类型',
            fgMainProperty: false,
            showOrder: 14,
            refAttributeName: 'dataType',
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '数据类型',
              displayProp: 'code',
              backWriteProp: 'idDataType',
              tableRef: {
                dataUri: '/dataType/aqPage',
                tableMainProp: 'idDataType',
                idComponentEntity: 'cTJfrDaUS3jn7tjORhO_4',
                ceDisplayName: '数据类型',
                refColumns: [
                  {
                    idBillRefColumn: 'm-lmJPBWwp3WR96FzBgcJ',
                    name: 'code',
                    displayName: '数据类型编码',
                  },
                  {
                    idBillRefColumn: 'MrkCA7Glj21Wb8M0hfcx2',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                  {
                    idBillRefColumn: 'TsnR_-5KZQjF2qZHNbyI1',
                    name: 'columnType',
                    displayName: '字段类型',
                  },
                ],
              },
            },
            fgDisplay: true,
            width: 150,
            textLen: 140,
          },
          {
            idBillFormField: 's8chLZ48BEGnurvPlY-rw',
            name: 'idRefEntity',
            dataType: 'InternalRef',
            displayName: '上级实体信息',
            fgMainProperty: false,
            showOrder: 15,
            refAttributeName: 'refEntity',
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '实体信息',
              displayProp: 'displayName',
              backWriteProp: 'idEntity',
              tableRef: {
                dataUri: '/ddEntity/aqPage',
                tableMainProp: 'idEntity',
                idComponentEntity: '0000-10940214-e5d9-4dce-b707-191e200c695f',
                ceDisplayName: '实体信息',
                refColumns: [
                  {
                    idBillRefColumn: '-8UYieWfmQmBKzzP6LmwI',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                  {
                    idBillRefColumn: 'r30mfWsR-WXCAIScOtYeU',
                    name: 'className',
                    displayName: '类名',
                  },
                  {
                    idBillRefColumn: 'qgrwAgFmPaT2I134NmDR0',
                    name: 'tableName',
                    displayName: '表名',
                  },
                ],
              },
            },
            fgDisplay: true,
            width: 150,
            textLen: 140,
          },
        ],
        metadataAttrName: 'commonAttribute',
        firstUpperTabCode: 'CommonAttribute',
        fgDefaultTab: true,
        tabClassName: 'CommonAttribute',
        firstLowerTabClassName: 'commonAttribute',
        tabAttrName: 'commonAttribute',
        firstUpperTabAttrName: 'CommonAttribute',
        mainProperty: 'idCommonAttribute',
        refType: 'Single',
        orderProperty: 'sn',
        orderType: 'ASC',
        orderInfoList: [
          {
            idOrderInfo: 'NR36tqkRg5e-yOcLlLOvx',
            orderProperty: 'idProject',
            orderType: 'ASC',
          },
          {
            idOrderInfo: '804Qqtc0HTY-F6pQgBOKY',
            orderProperty: 'sn',
            orderType: 'ASC',
          },
        ],
      },
    ],
    body: [],
    tail: [],
    uriConf: {
      fetchById: '/commonAttribute/getById',
      save: '/commonAttribute/add',
      update: '/commonAttribute/update',
      dataRemove: '/commonAttribute/remove',
    },
  },
};

export { tableConf };
