import { TActionContent } from '@/models';

const actionFormConf: TActionContent | undefined = {
  action: 1,
  componentModuleName: '系统模块',
  componentName: null,
  displayName: '菜单编辑按钮',
  idButtonAction: '9KVIgtP5x1TBIpK4HnhIu',
  idComponent: 'KIqhMnW5IZ8yYjy8Qu0ld',
  idComponentModule: 'NUWZLV-HXSQY7up9bY58k',
  idProject: '0000-fe135b87-fb33-481f-81a6-53dff1808f43',
  idSubProject: '0000-bb004a40-3b38-4c9c-9f30-b69a543b0598',
  name: 'menu_edit_action',
  projectName: '模板代码设计工具RUST',
  subProjectName: '模型管理',
  buttons: [
    {
      label: '保存',
      clickEventName: 'handleSave',
      disableScript: '',
      idButton: 'sI5tS0d7ihw9j5-YG0r1B',
      buttonSize: 'middle',
      type: 'primary',
      showOrder: 0,
      nameScript: "'保存'",
    },
    {
      label: '保存并新增',
      clickEventName: 'handleAddAgain',
      disableScript: '',
      hiddenScript: '!fgAdd',
      idButton: 'ug5xSgA8KYPlF_vQXB4hn',
      buttonSize: 'middle',
      type: 'primary',
      showOrder: 1,
      nameScript: "'保存并新增'",
    },
    {
      label: '取消',
      clickEventName: 'handleCancel',
      disableScript: '',
      idButton: 'Gs8JqPNCBIi4DGkpI2fjT',
      buttonSize: 'middle',
      type: 'primary',
      showOrder: 2,
      nameScript: "'取消'",
    },
    {
      label: '刷新',
      clickEventName: 'handleReflesh',
      disableScript: '',
      hiddenScript: '!fgAdd',
      idButton: 'HMzkOgJVcEj1a6x8oUFBn',
      buttonSize: 'middle',
      type: 'primary',
      showOrder: 3,
      nameScript: "'刷新'",
    },
  ],
  gap: '10px',
  justifyContent: 'start',
};

export { actionFormConf };
