import { TBillFormContent } from '@/models';

const billformConf: TBillFormContent | undefined = {
  action: 1,
  billFormType: 'Single',
  componentModuleName: '系统模块',
  componentName: '系统菜单',
  displayName: '系统菜单',
  idBillForm: 'sOGFb8hc2U8WZVy4ISJkT',
  idComponent: 'KIqhMnW5IZ8yYjy8Qu0ld',
  idComponentModule: 'NUWZLV-HXSQY7up9bY58k',
  idProject: '0000-fe135b87-fb33-481f-81a6-53dff1808f43',
  idSubProject: '0000-bb004a40-3b38-4c9c-9f30-b69a543b0598',
  name: 'Menu',
  projectName: '模板代码设计工具RUST',
  subProjectName: '模型管理',
  configList: {
    idBillForm: '43EdJmMUozLX6WXgAMulC',
    name: 'newBill',
    displayName: '新表单',
    header: [
      {
        idAttribute: 'mG8I2qeOw8wYPeMTVSksA',
        tabClassName: 'Menu',
        firstLowerTabClassName: 'menu',
        tabAttrName: 'menu',
        firstUpperTabAttrName: 'Menu',
        mainProperty: 'idMenu',
        tabCode: 'menu',
        firstUpperTabCode: 'Menu',
        tabName: '系统菜单',
        refType: 'Single',
        billFormFields: [
          {
            idBillFormField: 'q-2UmCczD9DKLH5FAQs3-',
            name: 'idMenu',
            displayName: '系统菜单id',
            fgMainProperty: true,
            showOrder: 0,
            readonly: false,
            dataType: 'PK',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '系统菜单id',
          },
          {
            idBillFormField: 'OD8Y6oYnpfR8_x_XzeWgb',
            name: 'name',
            displayName: '名称',
            fgMainProperty: false,
            showOrder: 1,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '名称',
          },
          {
            idBillFormField: 'kwY06Kv5n7puRNM7v_xls',
            name: 'displayName',
            displayName: '显示名称',
            fgMainProperty: false,
            showOrder: 2,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '显示名称',
          },
          {
            idBillFormField: 'Alc5dRGZXK53L2exc2vsN',
            name: 'fgShow',
            displayName: '显示标志',
            fgMainProperty: false,
            showOrder: 3,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '显示标志',
          },
          {
            idBillFormField: 'aHhTGEsDqeDQ6mliAojdN',
            name: 'query',
            displayName: '路由参数',
            fgMainProperty: false,
            showOrder: 4,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '路由参数',
          },
          {
            idBillFormField: 'O8UEAfr-Snctgj2htTnbQ',
            name: 'menuType',
            displayName: '菜单类型',
            fgMainProperty: false,
            showOrder: 5,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '菜单类型',
          },
          {
            idBillFormField: 'VatpT8RUNbxO2To9fwk-s',
            name: 'fgActive',
            displayName: '启用标志',
            fgMainProperty: false,
            showOrder: 6,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '启用标志',
            defaultValue: 'true',
          },
          {
            idBillFormField: 'f7SRtkl904P5mxEunFLWo',
            name: 'webPerms',
            displayName: '前端权限标识',
            fgMainProperty: false,
            showOrder: 7,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '前端权限标识',
          },
          {
            idBillFormField: 'rS9BHoITH9Z4cD-7yNWqL',
            name: 'servicePerms',
            displayName: '后台权限标识',
            fgMainProperty: false,
            showOrder: 8,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '后台权限标识',
          },
          {
            idBillFormField: '0W9ksCChDz0wNRQOuWQOA',
            name: 'idParent',
            dataType: 'InternalRef',
            displayName: '上级系统菜单',
            fgMainProperty: false,
            showOrder: 9,
            refAttributeName: 'parent',
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '系统菜单',
              displayProp: 'displayName',
              backWriteProp: 'idMenu',
              tableRef: {
                dataUri: '/menu/aqPage',
                tableMainProp: 'idMenu',
                idComponentEntity: 'UkyyDdtzsjoEluOjvY3l-',
                ceDisplayName: '系统菜单',
                refColumns: [
                  {
                    idBillRefColumn: 'plSPo_P5Yq1j1FEcEOaDY',
                    name: 'idMenu',
                    displayName: '系统菜单id',
                  },
                  {
                    idBillRefColumn: 'h2qO-DTCffB28ltQOPvAl',
                    name: 'name',
                    displayName: '名称',
                  },
                  {
                    idBillRefColumn: 'mUXOyHv2SFgCWC6g8ogTZ',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                ],
              },
            },
            fgDisplay: true,
            width: 150,
            textLen: 140,
            fgTreeAttr: true,
          },
        ],
        idBillFormTab: '8VoGIrep2EOiF23FCXUsE',
        tabIndex: 0,
        fgDefaultTab: true,
        orderInfoList: [
          {
            idOrderInfo: 'FGZVDS1I2wacSfEQxc-aU',
            orderProperty: 'idMenu',
            orderType: 'ASC',
          },
        ],
      },
    ],
    body: [],
    tail: [],
    uriConf: {
      page: '/menu/aqPage',
      fetchById: '/menu/extGetById',
      batchRemove: '/menu/batchRemove',
    },
  },
  configForm: {
    idBillForm: '43EdJmMUozLX6WXgAMulC',
    name: 'newBill',
    displayName: '新表单',
    header: [
      {
        idAttribute: 'mG8I2qeOw8wYPeMTVSksA',
        tabClassName: 'Menu',
        firstLowerTabClassName: 'menu',
        tabAttrName: 'menu',
        firstUpperTabAttrName: 'Menu',
        mainProperty: 'idMenu',
        tabCode: 'menu',
        firstUpperTabCode: 'Menu',
        tabName: '系统菜单',
        refType: 'Single',
        billFormFields: [
          {
            idBillFormField: 'q-2UmCczD9DKLH5FAQs3-',
            name: 'idMenu',
            displayName: '系统菜单id',
            fgMainProperty: true,
            showOrder: 0,
            readonly: false,
            dataType: 'PK',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '系统菜单id',
          },
          {
            idBillFormField: 'OD8Y6oYnpfR8_x_XzeWgb',
            name: 'name',
            displayName: '名称',
            fgMainProperty: false,
            showOrder: 1,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '名称',
          },
          {
            idBillFormField: 'kwY06Kv5n7puRNM7v_xls',
            name: 'displayName',
            displayName: '显示名称',
            fgMainProperty: false,
            showOrder: 2,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '显示名称',
          },
          {
            idBillFormField: 'Alc5dRGZXK53L2exc2vsN',
            name: 'fgShow',
            displayName: '显示标志',
            fgMainProperty: false,
            showOrder: 3,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '显示标志',
          },
          {
            idBillFormField: 'aHhTGEsDqeDQ6mliAojdN',
            name: 'query',
            displayName: '路由参数',
            fgMainProperty: false,
            showOrder: 4,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '路由参数',
          },
          {
            idBillFormField: 'O8UEAfr-Snctgj2htTnbQ',
            name: 'menuType',
            displayName: '菜单类型',
            fgMainProperty: false,
            showOrder: 5,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '菜单类型',
          },
          {
            idBillFormField: 'VatpT8RUNbxO2To9fwk-s',
            name: 'fgActive',
            displayName: '启用标志',
            fgMainProperty: false,
            showOrder: 6,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '启用标志',
            defaultValue: 'true',
          },
          {
            idBillFormField: 'f7SRtkl904P5mxEunFLWo',
            name: 'webPerms',
            displayName: '前端权限标识',
            fgMainProperty: false,
            showOrder: 7,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '前端权限标识',
          },
          {
            idBillFormField: 'rS9BHoITH9Z4cD-7yNWqL',
            name: 'servicePerms',
            displayName: '后台权限标识',
            fgMainProperty: false,
            showOrder: 8,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '后台权限标识',
          },
          {
            idBillFormField: '0W9ksCChDz0wNRQOuWQOA',
            name: 'idParent',
            dataType: 'InternalRef',
            displayName: '上级系统菜单',
            fgMainProperty: false,
            showOrder: 9,
            refAttributeName: 'parent',
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '系统菜单',
              displayProp: 'displayName',
              backWriteProp: 'idMenu',
              tableRef: {
                dataUri: '/menu/aqPage',
                tableMainProp: 'idMenu',
                idComponentEntity: 'UkyyDdtzsjoEluOjvY3l-',
                ceDisplayName: '系统菜单',
                refColumns: [
                  {
                    idBillRefColumn: 'plSPo_P5Yq1j1FEcEOaDY',
                    name: 'idMenu',
                    displayName: '系统菜单id',
                  },
                  {
                    idBillRefColumn: 'h2qO-DTCffB28ltQOPvAl',
                    name: 'name',
                    displayName: '名称',
                  },
                  {
                    idBillRefColumn: 'mUXOyHv2SFgCWC6g8ogTZ',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                ],
              },
            },
            fgDisplay: true,
            width: 150,
            textLen: 140,
            fgTreeAttr: true,
          },
        ],
        idBillFormTab: '8VoGIrep2EOiF23FCXUsE',
        tabIndex: 0,
        fgDefaultTab: true,
        orderInfoList: [
          {
            idOrderInfo: 'FGZVDS1I2wacSfEQxc-aU',
            orderProperty: 'idMenu',
            orderType: 'ASC',
          },
        ],
      },
    ],
    body: [],
    tail: [],
    uriConf: {
      fetchById: '/menu/getById',
      save: '/menu/add',
      update: '/menu/update',
      dataRemove: '/menu/remove',
    },
  },
};

export { billformConf };
