import { TUiFactoryContent } from '@/models';

const layoutConf: TUiFactoryContent = {
  action: 1,
  componentModuleName: '系统模块',
  componentName: null,
  displayName: '系统菜单',
  fgTemplate: false,
  idComponent: 'KIqhMnW5IZ8yYjy8Qu0ld',
  idComponentModule: 'NUWZLV-HXSQY7up9bY58k',
  idFactory: 'sUzEaCiafTj60Cr5cstG5',
  idProject: '0000-fe135b87-fb33-481f-81a6-53dff1808f43',
  idSubProject: '0000-bb004a40-3b38-4c9c-9f30-b69a543b0598',
  name: 'Menu',
  projectName: '模板代码设计工具RUST',
  refIdContent:
    '{"idViewBillform":"sOGFb8hc2U8WZVy4ISJkT","idEditBillform":"sOGFb8hc2U8WZVy4ISJkT","idTree":"sA1_14hfKg8CHhFB12BQg","idEditButtonAction":"_cWBpq9kJwJMQbnRf2oe4"}',
  subProjectName: '模型管理',
  pages: [
    { key: 'index', id: 'index', code: 'index', name: '首页' },
    {
      key: 'hsk2BULOi0Ccsu_PywOWj',
      id: 'hsk2BULOi0Ccsu_PywOWj',
      code: 'edit',
      name: '编辑页',
    },
  ],
  layouts: [
    {
      key: 'root',
      id: 'root',
      title: 'root',
      idParent: null,
      order: 1,
      type: 'layout',
      direction: 'row',
      flexType: 'auto',
      flexStr: '1 1 auto',
      children: [
        {
          key: 'v_l2bb0riiNJaVtsypzW4',
          id: 'v_l2bb0riiNJaVtsypzW4',
          title: '布局1',
          idParent: 'root',
          order: 1,
          type: 'component',
          direction: 'row',
          flexType: 'custom',
          flexStr: '0 0 300px',
          children: [],
          component: {
            componentType: 'tree',
            idRef: 'sA1_14hfKg8CHhFB12BQg',
            name: '系统菜单',
          },
          pageMaps: [
            {
              idPageMap: '69476d4a-9b4d-43ca-9e6a-ce9413f7304a',
              componentStateCode: 'list',
              pageCode: 'index',
            },
            {
              idPageMap: '36107824-c5c1-4b64-9fd2-c6634041896e',
              componentStateCode: 'form',
              pageCode: 'edit',
            },
          ],
        },
        {
          key: 'NBWOrTIk2VJPRAtdPje1j',
          id: 'NBWOrTIk2VJPRAtdPje1j',
          title: '布局2',
          idParent: 'root',
          order: 2,
          type: 'layout',
          direction: 'column',
          flexType: 'auto',
          flexStr: '1 1 auto',
          children: [
            {
              key: 'lZ6VLNjIwPx0aCk9Cxy6W',
              id: 'lZ6VLNjIwPx0aCk9Cxy6W',
              title: '布局3',
              idParent: 'NBWOrTIk2VJPRAtdPje1j',
              order: 1,
              type: 'component',
              direction: 'row',
              flexType: 'notGrow',
              flexStr: '0 1 auto',
              children: [],
              component: {
                componentType: 'editButton',
                idRef: '9KVIgtP5x1TBIpK4HnhIu',
                name: '菜单编辑按钮',
              },
            },
            {
              key: 'haQYNMKC0hlnmN4ncFpa0',
              id: 'haQYNMKC0hlnmN4ncFpa0',
              title: '布局4',
              idParent: 'NBWOrTIk2VJPRAtdPje1j',
              order: 2,
              type: 'component',
              direction: 'row',
              flexType: 'auto',
              flexStr: '1 1 auto',
              children: [],
              component: {
                componentType: 'editBillform',
                idRef: 'sOGFb8hc2U8WZVy4ISJkT',
                name: '系统菜单',
              },
              pageMaps: [
                {
                  idPageMap: 'd9be75de-7ab2-4db2-878d-42a74c98defc',
                  componentStateCode: 'list',
                  pageCode: 'index',
                },
                {
                  idPageMap: '89dd8789-b237-4c24-8371-ccfb27a331ed',
                  componentStateCode: 'form',
                  pageCode: 'edit',
                },
              ],
            },
            {
              key: '1JUxo2kEtqlRHdTbRKv0Z',
              id: '1JUxo2kEtqlRHdTbRKv0Z',
              title: '布局5',
              idParent: 'NBWOrTIk2VJPRAtdPje1j',
              order: 3,
              type: 'component',
              direction: 'row',
              flexType: 'auto',
              flexStr: '1 1 auto',
              children: [],
              component: {
                componentType: 'viewBillform',
                idRef: 'sOGFb8hc2U8WZVy4ISJkT',
                name: '系统菜单',
              },
            },
          ],
        },
      ],
    },
  ],
  assos: [
    { idPage: 'index', idLayout: 'root', hidden: false, disabled: false },
    {
      idPage: 'index',
      idLayout: 'v_l2bb0riiNJaVtsypzW4',
      hidden: false,
      disabled: false,
    },
    {
      idPage: 'index',
      idLayout: 'NBWOrTIk2VJPRAtdPje1j',
      hidden: false,
      disabled: false,
    },
    {
      idPage: 'index',
      idLayout: 'lZ6VLNjIwPx0aCk9Cxy6W',
      hidden: false,
      disabled: true,
    },
    {
      idPage: 'index',
      idLayout: 'haQYNMKC0hlnmN4ncFpa0',
      hidden: false,
      disabled: true,
    },
    {
      idPage: 'hsk2BULOi0Ccsu_PywOWj',
      idLayout: 'v_l2bb0riiNJaVtsypzW4',
      hidden: false,
      disabled: true,
    },
    {
      idPage: 'hsk2BULOi0Ccsu_PywOWj',
      idLayout: 'lZ6VLNjIwPx0aCk9Cxy6W',
      hidden: false,
      disabled: false,
    },
    {
      idPage: 'hsk2BULOi0Ccsu_PywOWj',
      idLayout: 'haQYNMKC0hlnmN4ncFpa0',
      hidden: false,
      disabled: false,
    },
    {
      idPage: 'hsk2BULOi0Ccsu_PywOWj',
      idLayout: 'NBWOrTIk2VJPRAtdPje1j',
      hidden: false,
      disabled: false,
    },
    {
      idPage: 'hsk2BULOi0Ccsu_PywOWj',
      idLayout: 'root',
      hidden: false,
      disabled: false,
    },
    {
      idPage: 'index',
      idLayout: '1JUxo2kEtqlRHdTbRKv0Z',
      hidden: true,
      disabled: false,
    },
    {
      idPage: 'hsk2BULOi0Ccsu_PywOWj',
      idLayout: '1JUxo2kEtqlRHdTbRKv0Z',
      hidden: true,
      disabled: false,
    },
  ],
};

export { layoutConf };
