import { TBillFormContent } from '@/models';

const billformConf: TBillFormContent | undefined = {
  action: 1,
  billFormType: 'Single',
  componentModuleName: '公共属性',
  componentName: '数据类型',
  displayName: '数据类型',
  idBillForm: '7Qr7imQHM2bULYzpDez6L',
  idComponent: '0000-115f0f9f-1acf-4113-9d63-534cedc06fe8',
  idComponentModule: '0000-ae91cf86-2dba-4906-8fbc-b5e35d71909a',
  idProject: '0000-fe135b87-fb33-481f-81a6-53dff1808f43',
  idSubProject: '0000-bb004a40-3b38-4c9c-9f30-b69a543b0598',
  name: 'AttributeType',
  projectName: '模板代码设计工具RUST',
  subProjectName: '模型管理',
  configList: {
    idBillForm: 'uuDgPKneXJ0-JUIlNLylO',
    name: 'newBill',
    displayName: '新表单',
    header: [
      {
        idBillFormTab: 'fVzvpGVenymcuxlZeRKDZ',
        tabCode: 'dataType',
        tabName: '数据类型',
        tabIndex: 0,
        billFormFields: [
          {
            idBillFormField: 'yP7-R69Os2jLw-lmfW9Uv',
            name: 'idDataType',
            displayName: '数据类型id',
            fgMainProperty: true,
            showOrder: 0,
            readonly: true,
            dataType: 'PK',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '数据类型id',
          },
          {
            idBillFormField: 'VITsgvRCyCLiNdA7witbt',
            name: 'code',
            displayName: '数据类型编码',
            fgMainProperty: false,
            showOrder: 1,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '数据类型编码',
          },
          {
            idBillFormField: 'RHRwvMx-UzFkStvrs77LT',
            name: 'displayName',
            displayName: '显示名称',
            fgMainProperty: false,
            showOrder: 2,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '显示名称',
          },
          {
            idBillFormField: 'FVGmvpuC8cQi7LtdlwNU-',
            name: 'note',
            displayName: '备注',
            fgMainProperty: false,
            showOrder: 3,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '备注',
          },
          {
            idBillFormField: 'gXTXnL-7HHVODK4D3_x_e',
            name: 'sn',
            displayName: '序列号',
            fgMainProperty: false,
            showOrder: 4,
            readonly: false,
            dataType: 'Integer',
            inputType: 'InputNumber',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '序列号',
          },
          {
            idBillFormField: 'N_sgY1bmBeCC-h3VOp2XR',
            name: 'len',
            displayName: '长度',
            fgMainProperty: false,
            showOrder: 5,
            readonly: false,
            dataType: 'Integer',
            inputType: 'InputNumber',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '长度',
          },
          {
            idBillFormField: 'OaYk_L9iRxo6kiYt1EmkT',
            name: 'pcs',
            displayName: '精度',
            fgMainProperty: false,
            showOrder: 6,
            readonly: false,
            dataType: 'Integer',
            inputType: 'InputNumber',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '精度',
          },
          {
            idBillFormField: 'm2xI0pqEIKjp4hjO9aKZV',
            name: 'columnType',
            displayName: '字段类型',
            fgMainProperty: false,
            showOrder: 7,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '字段类型',
          },
          {
            idBillFormField: 'KbLGEW8jvZKD0KNfeBnU9',
            name: 'objectType',
            displayName: '对象类型名称',
            fgMainProperty: false,
            showOrder: 8,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '对象类型名称',
          },
          {
            idBillFormField: 'FAE4tZNBxL-leQIXwKj1_',
            name: 'objectTypePackage',
            displayName: '对象类型包名',
            fgMainProperty: false,
            showOrder: 9,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '对象类型包名',
          },
          {
            idBillFormField: '8rI3Tjd5ZF-DrwuoCOvp-',
            name: 'ext1',
            displayName: '扩展属性1',
            fgMainProperty: false,
            showOrder: 10,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '扩展属性1',
          },
          {
            idBillFormField: 'JAWj63T5i_ppIEywSR7GC',
            name: 'ext2',
            displayName: '扩展属性2',
            fgMainProperty: false,
            showOrder: 11,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '扩展属性2',
          },
          {
            idBillFormField: 'LHSWVBWraBJNCv20lZ53C',
            name: 'ext3',
            displayName: '扩展属性3',
            fgMainProperty: false,
            showOrder: 12,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '扩展属性3',
          },
          {
            idBillFormField: 'XEovhTVi-OgDuquyL132O',
            name: 'ext4',
            displayName: '扩展属性4',
            fgMainProperty: false,
            showOrder: 13,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '扩展属性4',
          },
          {
            idBillFormField: 'Wp1MnTkmvqd6jPkpE_RK2',
            name: 'ext5',
            displayName: '扩展属性5',
            fgMainProperty: false,
            showOrder: 14,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '扩展属性5',
          },
          {
            idBillFormField: 'sa3NvRpo7nMOB8HMvX-kH',
            name: 'ext6',
            displayName: '扩展属性6',
            fgMainProperty: false,
            showOrder: 15,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '扩展属性6',
          },
          {
            idBillFormField: 'tS6G5NPuICV9hIPIbNqK3',
            name: 'defaultValue',
            displayName: '默认值',
            fgMainProperty: false,
            showOrder: 16,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '默认值',
          },
          {
            idBillFormField: 'dxtcBd6fJad-M1TX8otE6',
            name: 'fgMandatory',
            displayName: '必填标志',
            fgMainProperty: false,
            showOrder: 17,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '必填标志',
          },
          {
            idBillFormField: '8bpTn23gWEGl79FSMr7T8',
            name: 'typeScriptType',
            displayName: 'TypeScript类型',
            fgMainProperty: false,
            showOrder: 18,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: 'TypeScript类型',
          },
          {
            idBillFormField: 'F7BvFnR4pxCarjn8T4vr7',
            name: 'webInputType',
            displayName: 'HTML5输入框类型',
            fgMainProperty: false,
            showOrder: 19,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: 'HTML5输入框类型',
          },
          {
            idBillFormField: 'Sx8BB65gsAchKxmqzuOlc',
            name: 'fgPreset',
            displayName: '系统预置数据标识',
            fgMainProperty: false,
            showOrder: 20,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '系统预置数据标识',
            defaultValue: 'false',
          },
          {
            idBillFormField: 'qJ89oPPXA8tHdP-V5JUz0',
            name: 'idProject',
            dataType: 'InternalRef',
            displayName: '项目',
            fgMainProperty: false,
            showOrder: 21,
            refAttributeName: 'project',
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '项目',
              displayProp: 'code',
              backWriteProp: 'idProject',
              tableRef: {
                dataUri: '/project/aqPage',
                tableMainProp: 'idProject',
                idComponentEntity: '0000-c42a3d77-90bd-4e33-8618-dc6b746109f7',
                ceDisplayName: '项目',
                refColumns: [
                  {
                    idBillRefColumn: 'yS3gisyLmmBvMp4uvsKUu',
                    name: 'code',
                    displayName: '项目编号',
                  },
                  {
                    idBillRefColumn: '73loh45ouEn8BgUxWIDt7',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                  {
                    idBillRefColumn: 'jOgbBHE2s0EaS5yugcilW',
                    name: 'fileNameType',
                    displayName: '文件名样式',
                  },
                  {
                    idBillRefColumn: 'OejNrigALVQgty4FznAe8',
                    name: 'templateCode',
                    displayName: '项目模板编号',
                  },
                ],
              },
            },
            fgDisplay: true,
            width: 150,
            textLen: 140,
            fgTreeAttr: true,
          },
        ],
        metadataAttrName: 'dataType',
        firstUpperTabCode: 'DataType',
        fgDefaultTab: true,
        tabClassName: 'DataType',
        firstLowerTabClassName: 'dataType',
        tabAttrName: 'dataType',
        firstUpperTabAttrName: 'DataType',
        mainProperty: 'idDataType',
        refType: 'Single',
        orderProperty: 'sn',
        orderType: 'ASC',
        orderInfoList: [
          {
            idOrderInfo: 'o8preN06kGy5_XMBFJTwc',
            orderProperty: 'idProject',
            orderType: 'ASC',
          },
          {
            idOrderInfo: 'oybWP27Gkt2qWQiwlz71L',
            orderProperty: 'sn',
            orderType: 'ASC',
          },
        ],
      },
    ],
    body: [],
    tail: [],
    uriConf: {
      page: '/dataType/aqPage',
      fetchById: '/dataType/getById',
      batchRemove: '/dataType/batchRemove',
    },
  },
  configForm: {
    idBillForm: 'uuDgPKneXJ0-JUIlNLylO',
    name: 'newBill',
    displayName: '新表单',
    header: [
      {
        idBillFormTab: 'fVzvpGVenymcuxlZeRKDZ',
        tabCode: 'dataType',
        tabName: '数据类型',
        tabIndex: 0,
        billFormFields: [
          {
            idBillFormField: 'yP7-R69Os2jLw-lmfW9Uv',
            name: 'idDataType',
            displayName: '数据类型id',
            fgMainProperty: true,
            showOrder: 0,
            readonly: true,
            dataType: 'PK',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '数据类型id',
          },
          {
            idBillFormField: 'VITsgvRCyCLiNdA7witbt',
            name: 'code',
            displayName: '数据类型编码',
            fgMainProperty: false,
            showOrder: 1,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '数据类型编码',
          },
          {
            idBillFormField: 'RHRwvMx-UzFkStvrs77LT',
            name: 'displayName',
            displayName: '显示名称',
            fgMainProperty: false,
            showOrder: 2,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '显示名称',
          },
          {
            idBillFormField: 'FVGmvpuC8cQi7LtdlwNU-',
            name: 'note',
            displayName: '备注',
            fgMainProperty: false,
            showOrder: 3,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '备注',
          },
          {
            idBillFormField: 'gXTXnL-7HHVODK4D3_x_e',
            name: 'sn',
            displayName: '序列号',
            fgMainProperty: false,
            showOrder: 4,
            readonly: false,
            dataType: 'Integer',
            inputType: 'InputNumber',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '序列号',
          },
          {
            idBillFormField: 'N_sgY1bmBeCC-h3VOp2XR',
            name: 'len',
            displayName: '长度',
            fgMainProperty: false,
            showOrder: 5,
            readonly: false,
            dataType: 'Integer',
            inputType: 'InputNumber',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '长度',
          },
          {
            idBillFormField: 'OaYk_L9iRxo6kiYt1EmkT',
            name: 'pcs',
            displayName: '精度',
            fgMainProperty: false,
            showOrder: 6,
            readonly: false,
            dataType: 'Integer',
            inputType: 'InputNumber',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '精度',
          },
          {
            idBillFormField: 'm2xI0pqEIKjp4hjO9aKZV',
            name: 'columnType',
            displayName: '字段类型',
            fgMainProperty: false,
            showOrder: 7,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '字段类型',
          },
          {
            idBillFormField: 'KbLGEW8jvZKD0KNfeBnU9',
            name: 'objectType',
            displayName: '对象类型名称',
            fgMainProperty: false,
            showOrder: 8,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '对象类型名称',
          },
          {
            idBillFormField: 'FAE4tZNBxL-leQIXwKj1_',
            name: 'objectTypePackage',
            displayName: '对象类型包名',
            fgMainProperty: false,
            showOrder: 9,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '对象类型包名',
          },
          {
            idBillFormField: '8rI3Tjd5ZF-DrwuoCOvp-',
            name: 'ext1',
            displayName: '扩展属性1',
            fgMainProperty: false,
            showOrder: 10,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '扩展属性1',
          },
          {
            idBillFormField: 'JAWj63T5i_ppIEywSR7GC',
            name: 'ext2',
            displayName: '扩展属性2',
            fgMainProperty: false,
            showOrder: 11,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '扩展属性2',
          },
          {
            idBillFormField: 'LHSWVBWraBJNCv20lZ53C',
            name: 'ext3',
            displayName: '扩展属性3',
            fgMainProperty: false,
            showOrder: 12,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '扩展属性3',
          },
          {
            idBillFormField: 'XEovhTVi-OgDuquyL132O',
            name: 'ext4',
            displayName: '扩展属性4',
            fgMainProperty: false,
            showOrder: 13,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '扩展属性4',
          },
          {
            idBillFormField: 'Wp1MnTkmvqd6jPkpE_RK2',
            name: 'ext5',
            displayName: '扩展属性5',
            fgMainProperty: false,
            showOrder: 14,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '扩展属性5',
          },
          {
            idBillFormField: 'sa3NvRpo7nMOB8HMvX-kH',
            name: 'ext6',
            displayName: '扩展属性6',
            fgMainProperty: false,
            showOrder: 15,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '扩展属性6',
          },
          {
            idBillFormField: 'tS6G5NPuICV9hIPIbNqK3',
            name: 'defaultValue',
            displayName: '默认值',
            fgMainProperty: false,
            showOrder: 16,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '默认值',
          },
          {
            idBillFormField: 'dxtcBd6fJad-M1TX8otE6',
            name: 'fgMandatory',
            displayName: '必填标志',
            fgMainProperty: false,
            showOrder: 17,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '必填标志',
          },
          {
            idBillFormField: '8bpTn23gWEGl79FSMr7T8',
            name: 'typeScriptType',
            displayName: 'TypeScript类型',
            fgMainProperty: false,
            showOrder: 18,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: 'TypeScript类型',
          },
          {
            idBillFormField: 'F7BvFnR4pxCarjn8T4vr7',
            name: 'webInputType',
            displayName: 'HTML5输入框类型',
            fgMainProperty: false,
            showOrder: 19,
            readonly: false,
            dataType: 'String',
            inputType: 'Input',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: 'HTML5输入框类型',
          },
          {
            idBillFormField: 'Sx8BB65gsAchKxmqzuOlc',
            name: 'fgPreset',
            displayName: '系统预置数据标识',
            fgMainProperty: false,
            showOrder: 20,
            readonly: false,
            dataType: 'Boolean',
            inputType: 'Checkbox',
            fgDisplay: true,
            width: 150,
            textLen: 140,
            placeholder: '系统预置数据标识',
            defaultValue: 'false',
          },
          {
            idBillFormField: 'qJ89oPPXA8tHdP-V5JUz0',
            name: 'idProject',
            dataType: 'InternalRef',
            displayName: '项目',
            fgMainProperty: false,
            showOrder: 21,
            refAttributeName: 'project',
            readonly: false,
            inputType: 'Ref',
            refConfig: {
              refStyle: 'table',
              title: '项目',
              displayProp: 'code',
              backWriteProp: 'idProject',
              tableRef: {
                dataUri: '/project/aqPage',
                tableMainProp: 'idProject',
                idComponentEntity: '0000-c42a3d77-90bd-4e33-8618-dc6b746109f7',
                ceDisplayName: '项目',
                refColumns: [
                  {
                    idBillRefColumn: 'yS3gisyLmmBvMp4uvsKUu',
                    name: 'code',
                    displayName: '项目编号',
                  },
                  {
                    idBillRefColumn: '73loh45ouEn8BgUxWIDt7',
                    name: 'displayName',
                    displayName: '显示名称',
                  },
                  {
                    idBillRefColumn: 'jOgbBHE2s0EaS5yugcilW',
                    name: 'fileNameType',
                    displayName: '文件名样式',
                  },
                  {
                    idBillRefColumn: 'OejNrigALVQgty4FznAe8',
                    name: 'templateCode',
                    displayName: '项目模板编号',
                  },
                ],
              },
            },
            fgDisplay: true,
            width: 150,
            textLen: 140,
            fgTreeAttr: true,
          },
        ],
        metadataAttrName: 'dataType',
        firstUpperTabCode: 'DataType',
        fgDefaultTab: true,
        tabClassName: 'DataType',
        firstLowerTabClassName: 'dataType',
        tabAttrName: 'dataType',
        firstUpperTabAttrName: 'DataType',
        mainProperty: 'idDataType',
        refType: 'Single',
        orderProperty: 'sn',
        orderType: 'ASC',
        orderInfoList: [
          {
            idOrderInfo: 'o8preN06kGy5_XMBFJTwc',
            orderProperty: 'idProject',
            orderType: 'ASC',
          },
          {
            idOrderInfo: 'oybWP27Gkt2qWQiwlz71L',
            orderProperty: 'sn',
            orderType: 'ASC',
          },
        ],
      },
    ],
    body: [],
    tail: [],
    uriConf: {
      fetchById: '/dataType/getById',
      save: '/dataType/add',
      update: '/dataType/update',
      dataRemove: '/dataType/remove',
    },
  },
};

export { billformConf };
